spring:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plr-record
    username: root
    password: 123456
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8443  # 使用 8443 端口，通常用于 HTTPS
  servlet:
    session:
      timeout: 180m
  ssl:
    key-store: classpath:ssl/grayplume.icu.pfx  # 证书文件路径
    key-store-password: ifs5pire  # 密码
    key-store-type: PKCS12  # PFX 格式
    key-alias: alias  # 如果有别名


weather:
  api-key: 5123b83956b04ca4b7ccb9cf14f9c953
  base-url: https://n37p3v7cgw.re.qweatherapi.com



